### PR TITLE
Dungeon game loop

### PR DESCRIPTION
**Pull request by RossBrunton**
The game starts in build place state, and then the player clicks "go" to start the heroes. Then they move from room to room triggering events.

### CODE REVIEW

**Comment by ChatBotMatt** [comment]
What's the `assert(false)` on line 51 of `game_scene.gd` for?

**Comment by ChatBotMatt** [comment]
Also, can we not get the room positions more dynamically?

**Comment by RossBrunton** [comment]
> What's the `assert(false)` on line 51 of `game_scene.gd` for?

It's an abort, in case the room index is illegal.

**Comment by RossBrunton** [comment]
> Also, can we not get the room positions more dynamically?

Yes, once we know how that actually works.

**Comment by ChatBotMatt** [comment]
When is it not going to abort upon that line?

**Comment by ChatBotMatt** [comment]
Ah wait, sorry, misread.

**Comment by ChatBotMatt** [comment]
Looks decent, will merge

**Pull request merged**
